#!/bin/bash

fsms_root_dir="$(dirname "$0")"
fsms_dir="$(pwd)/.fsms"

if [ "$1" == "init" ]; then
    echo "-=INIT=-"
    if [ -d ".fsms" ]; then
        echo "Error: The current folder is already being tracked"
        exit 1
    fi
    mkdir "$fsms_dir"
    cp "$(dirname "$0")/watcher.ini" "$fsms_dir"
    sed -i "s#watch =.*#watch = $(pwd)#" "$fsms_dir/watcher.ini"
    nano "$fsms_dir/watcher.ini"
    python3 "$fsms_root_dir/main.py" $(pwd) "start"
    echo "--------"
elif [ "$1" == "start" ]; then
    echo "-=STARTED=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "start"
    echo "-----------"
elif [ "$1" == "stop" ]; then
    echo "-=STOPED=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "stop"
    echo "----------"
elif [ "$1" == "status" ]; then
    echo "-=STATUS=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "status"
    echo "----------"
elif [ "$1" == "restart" ]; then
    echo "-=RESTART=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "restart"
    echo "-----------"
elif [ "$1" == "clear" ]; then
    echo "-=CLEARING=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "stop"
    rm -r $fsms_dir
    echo "------------"
else
    echo "The wrong command"
    echo "[help] 1.Enter the 'init' option. 2.Configure the configuration file"
    exit 1
fi