#!/bin/bash

fsms_root_dir="$(dirname "$0")"
fsms_dir="$(pwd)/.fsms"

if [ "$1" == "init" ]; then
    echo "-=INIT=-"
    if [ -d ".fsms" ]; then
        echo "Error: The current folder is already being tracked"
        exit 1
    fi
    mkdir "$fsms_dir"
    cp "$(dirname "$0")/watcher.ini" "$fsms_dir"
    sed -i "s#watch =.*#watch = $(pwd)#" "$fsms_dir/watcher.ini"
    nano "$fsms_dir/watcher.ini"
elif [ "$1" == "start" ]; then
    echo "-=STARTED=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "start"
elif [ "$1" == "stop" ]; then
    echo "-=STOPPED=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "stop"
elif [ "$1" == "status" ]; then
    echo "-=STATUS=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "status"
elif [ "$1" == "restart" ]; then
    echo "-=RESTART=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "restart"
elif [ "$1" == "clear" ]; then
    echo "-=CLEARING=-"
    python3 "$fsms_root_dir/main.py" $(pwd) "stop"
    rm -r $fsms_dir
elif [ "$1" == "help" ]; then
    echo "Usage: fsms <command>"
    echo "Available commands:"
    echo "  init       - Initialize tracking for the current directory"
    echo "  start      - Start monitoring for changes"
    echo "  stop       - Stop monitoring"
    echo "  status     - Check the status of monitoring"
    echo "  restart    - Restart monitoring"
    echo "  clear      - Stop monitoring and remove tracking configuration"
else
    echo "Error: Unknown command"
    echo "Type 'fsms help' for usage instructions"
    exit 1
fi